name: Push master
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: renlulu/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/zilliqa/zli/zli
          username: xiaohuo
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com