name: Integration Test Github
on: [push]
  branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build the Docker image
        run: docker build -t docker.pkg.github.com/zilliqa/zli/go-zli:latest .
      - name: Publish to Registry
        uses: renlulu/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/zilliqa/zli/go-zli:latest
          username: xiaohuo
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com